classDiagram   
    Web_Service --|> DAOUsers: request user data
    Web_Service --|> DAOChilds: request child data
    Web_Service --|> DAOTaps: request tap data
    DAOUsers --|> User: request user data
    DAOUsers <|-- User: return user data
    DAOUsers --|> Web_Service:  return user data
    DAOChilds --|> Child: request child data
    DAOChilds <|-- Child: return child data
    DAOChilds --|> Web_Service:  return child data
    DAOTaps --|> Taps: request tap data
    DAOTaps <|-- Taps: return tap data
    DAOTaps --|> Web_Service:  return tap data
    
    class DAOUsers{
        -listUsers
        +getUserByUserID(id)
    }
    class DAOChilds{
        -listChilds
        +getChildByUserID(id)
    }
    class DAOTaps{
        -listTaps
        +getTapByChildID(child_id)
    }
    class Web_Service{
        +showUserInfo(User)
        +showChildInfo(Child)
        +showTapInfo(Tap)
    }
    class User{
        -id int
        -username String
        -email String
        -password String
    }
    class Child{
        -child_id int
        -child_name string
        -sleep_average int
        -treatment_id int
        -patch_time int
        -state String
    }
    class Taps{
        -id int
        -child_id int
        -status_id int
        -user_id int
        -init Date
        -end Date
    }